apiVersion: apps/v1
kind: Deployment
metadata:
  name: ervcp
  namespace: ervcp
  labels:
    app: ervcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ervcp
  template:
    metadata:
      labels:
        app: ervcp
    spec:
      containers:
      - name: ervcp
        image: ataccamadevopstask.azurecr.io/ervcp
        imagePullPolicy: IfNotPresent
        env:
        - name: ERVCP_DB_PORT
          value: "6379"
        - name: ERVCP_DB_HOST
          value: "redis-master"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 1Gi
        ports:
        - containerPort: 8080
      imagePullSecrets: acr-secret
