apiVersion: v1
kind: Service
metadata:
  name: ervcp
  namespace: ervcp
  labels:
    app: ervcp
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: ervcp
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: ervcp
  type: LoadBalancer
