name: kubernetes-lint
on: [workflow_dispatch, push]

jobs:
  k8s-lint:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: 'kubeval'
        uses: azure/k8s-lint@v1
        with:
          manifests: |
            manifests/ervcp-deployment.yml
            manifests/ervcp-service.yml
            manifests/redis-deployment.yml
            manifests/redis-service.yml
